### ISSUE TITLE
Upgrade @mdx-js/mdx to v2 [critical security issue]

### ISSUE THREAD

**Issue by Tobi-mmt** [storybookjs/mdx1-csf#11]
**Describe the bug**
This project has a critical security issue.

It is currently using  `@mdx-js/mdx` in version 1.x which uses `remark-parse` which uses an insecure `trim` version. E.g. updating to `@mdx-js/mdx` version 2.x will fix that security issue.

**To Reproduce**
1. create new Project with `npm init`
2. Add the package `npm install --save @storybook/mdx1-csf`
3. Check for security issues `npm audit`
4. See high security issue

**Expected behavior**
No security issues in `@storybook/mdx1-csf`

**Screenshots**
![issue](https://user-images.githubusercontent.com/14888529/173551285-1c7f9d2b-3a8a-41d3-b0fd-fbe6e677f764.png)

**Comment by DamienCassou** [comment]
This is an issue for me as well.

**Comment by shilman** [comment]
This library is about interfacing with MDX1. For MDX2 there is a separate library https://github.com/storybookjs/mdx2-csf

Storybook itself will be upgrading to MDX2 in 7.0 (breaking change) which will fix the security audit.

Closing this for now.
